/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/account`; params?: Router.UnknownInputParams; } | { pathname: `/email-sent`; params?: Router.UnknownInputParams; } | { pathname: `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/scan`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/tutorial`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/animals/badge`; params?: Router.UnknownInputParams; } | { pathname: `/animals/checkpoint`; params?: Router.UnknownInputParams; } | { pathname: `/animals/reading`; params?: Router.UnknownInputParams; } | { pathname: `/animals/writing`; params?: Router.UnknownInputParams; } | { pathname: `/colors/badge`; params?: Router.UnknownInputParams; } | { pathname: `/colors/checkpoint`; params?: Router.UnknownInputParams; } | { pathname: `/colors/reading`; params?: Router.UnknownInputParams; } | { pathname: `/colors/writing`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/account`; params?: Router.UnknownOutputParams; } | { pathname: `/email-sent`; params?: Router.UnknownOutputParams; } | { pathname: `/forgot-password`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/scan`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/tutorial`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/animals/badge`; params?: Router.UnknownOutputParams; } | { pathname: `/animals/checkpoint`; params?: Router.UnknownOutputParams; } | { pathname: `/animals/reading`; params?: Router.UnknownOutputParams; } | { pathname: `/animals/writing`; params?: Router.UnknownOutputParams; } | { pathname: `/colors/badge`; params?: Router.UnknownOutputParams; } | { pathname: `/colors/checkpoint`; params?: Router.UnknownOutputParams; } | { pathname: `/colors/reading`; params?: Router.UnknownOutputParams; } | { pathname: `/colors/writing`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/account${`?${string}` | `#${string}` | ''}` | `/email-sent${`?${string}` | `#${string}` | ''}` | `/forgot-password${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/scan${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/tutorial${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/animals/badge${`?${string}` | `#${string}` | ''}` | `/animals/checkpoint${`?${string}` | `#${string}` | ''}` | `/animals/reading${`?${string}` | `#${string}` | ''}` | `/animals/writing${`?${string}` | `#${string}` | ''}` | `/colors/badge${`?${string}` | `#${string}` | ''}` | `/colors/checkpoint${`?${string}` | `#${string}` | ''}` | `/colors/reading${`?${string}` | `#${string}` | ''}` | `/colors/writing${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/account`; params?: Router.UnknownInputParams; } | { pathname: `/email-sent`; params?: Router.UnknownInputParams; } | { pathname: `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/scan`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/tutorial`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/animals/badge`; params?: Router.UnknownInputParams; } | { pathname: `/animals/checkpoint`; params?: Router.UnknownInputParams; } | { pathname: `/animals/reading`; params?: Router.UnknownInputParams; } | { pathname: `/animals/writing`; params?: Router.UnknownInputParams; } | { pathname: `/colors/badge`; params?: Router.UnknownInputParams; } | { pathname: `/colors/checkpoint`; params?: Router.UnknownInputParams; } | { pathname: `/colors/reading`; params?: Router.UnknownInputParams; } | { pathname: `/colors/writing`; params?: Router.UnknownInputParams; };
    }
  }
}
