FROM node:lts-alpine

WORKDIR /app

# Install expo-cli globally
RUN npm install -g expo-cli @expo/ngrok

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 8081 19000 19001 19002

CMD ["npx", "expo", "start", "--web"]
